import "../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div
          id="jsremote"
          dangerouslySetInnerHTML={{
            __html: `
          <script>
          window.remoteImport = (v) => import(v);
          </script>
          `,
          }}
        ></div>
        {children}
      </body>
    </html>
  )
}
